import type { Metadata } from "next";
import "./globals.css";
import {  Space_Grotesk } from "next/font/google";

const font = Space_Grotesk({
	subsets: ['latin-ext'],
	// display: 'swap', 
  // weight: "800"
});

export const metadata: Metadata = {
  title: "Status Projeto Vercel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" >
      <body suppressHydrationWarning className={`${font} `}>
        {children}
      </body>
    </html>
  );
}
